### ISSUE TITLE
Goal hidden when a higher one is also set

### ISSUE THREAD

**Issue by stp-ip** [bountysource/frontend#839]
When there is more than 1 goal, after the first one is funded it isn't clear that the goal was reached. It seems as if the goal was removed and the bigger one is the only one left. This seems real strange.
Make it clear that the first goal is reached and a second can be reached too.

**Comment by rappo** [comment]
All goals are now displayed, example: https://www.bountysource.com/issues/1424389-faces-support-200/developers
