### ISSUE TITLE
10% fee charged on cash out on donations from 2013

### ISSUE THREAD

**Issue by bjorn** [bountysource/frontend#911]
I just requested a cash-out to Bitcoin of $115 that I had received for resolving https://www.bountysource.com/issues/128179-animated-tiles. The backers are all from 2013, when they still had to pay a 10% fee to back the issue. However, on cashing out, the 10% fee was charged again (or at least so did the cash out page indicate, the actual cash out is still pending).

I'm not asking for a refund of the fee here, just wanted to make sure you were aware of this issue. I had done a larger cash out before in which case it correctly detected that the donations had been done before the change in when the fee is charged.

**Comment by rappo** [comment]
Hi @bjorn, we haven't seen or heard of this issue come up since your initial report in Sept. If you see anything unusual please let us know and we'll investigate. I'll close this since we haven't heard anything else.

**Comment by bjorn** [comment]
@rappo Understandable, especially since the fee change is now such a long time ago it would be very rare for somebody to run into this, as well as to even notice it if so.
