### ISSUE TITLE
Truncated project titles don't show up with mouseover (FF 30, Linux x64)

### ISSUE THREAD

**Issue by Overand** [bountysource/frontend#923]
At least in Firefox 30 on Linux, x64, truncated project names (see "Owncloud And..." below) don't show up on mouseover.

Example project:  https://www.bountysource.com/teams/owncloud

Possible fixes:  Add mouseover.
![2014-10-21-113811_1179x1114_scrot](https://cloud.githubusercontent.com/assets/3119819/4721636/e5a173d2-5939-11e4-87f5-a7354bde87d8.png)

**Comment by rappo** [comment]
"Our Projects" is no longer displayed, as each team should be one project team / group and the tracker-level data has been suppressed. No longer have the project titles to truncate.
