### ISSUE TITLE
Option for List-view instead of Grid-view for Projects/sub-projects (for ones with long names)

### ISSUE THREAD

**Issue by Overand** [bountysource/frontend#924]
Provide an option for either the user or the page / project maintaner to enable a list view instead of the grid view, for projects with very long titles.

(Alternately, automatically select this if titles have been truncated).

The situation below is sub-optimal from a usability standpoint.

![2014-10-21-113811_1179x1114_scrot](https://cloud.githubusercontent.com/assets/3119819/4721676/249322c0-593a-11e4-80c4-e6c257643431.png)

**Comment by GeoffMaciolek** [comment]
It looks to me like this section of the interface has been rebuilt; this issue can probably be closed.

**Comment by rappo** [comment]
The changes to the team home page since the original issue made this problem irrelevant, closing.
