### ISSUE TITLE
Firefox extension broken

### ISSUE THREAD

**Issue by orschiro** [bountysource/frontend#941]
Hi,

Just to report that the link to the [Firefox extension](https://www.bountysource.com/extension) is broken.

Regards,

Robert

**Comment by rappo** [comment]
Hi @orschiro, we received some feedback from Mozilla and need to resubmit the extension. We hope to have it resubmitted by Wednesday. It can take a while for their review, but the extension should be available immediately after submission (just not discoverable). We'll post as soon as it's back up!

**Comment by orschiro** [comment]
@rappo 

Thanks for clarifying!

Robert

**Comment by rappo** [comment]
The extension has been resubmitted and can be downloaded here: https://addons.mozilla.org/en-US/firefox/addon/bountysource/

I'll close this as soon as we get approval from Mozilla.

**Comment by orschiro** [comment]
@rappo 

Works perfectly. Thanks!

**Comment by rappo** [comment]
D'oh, forgot to close! We were approved by Mozilla. Happy thumbing :)
