### ISSUE TITLE
Qt bounty not showing anything.

### ISSUE THREAD

**Issue by eduardbeutel** [bountysource/frontend#959]
The Qt bounty https://www.bountysource.com/issues/315019-add-a-tiling-window-manager-like-eclipse-or-visual-studio-have is dead. It's probably the web scraper since Qt bugs moved to bugreports.qt.io.

**Comment by rappo** [comment]
Responded privately to the support ticket, but this is indeed related to Qt changing their issue tracker URL. The new issue is https://www.bountysource.com/issues/7571628-add-a-tiling-window-manager-like-eclipse-or-visual-studio-have and the bounties have been moved.

The team was already updated to reflect the changes, here: https://www.bountysource.com/teams/qt/issues?tracker_ids=13795429
